### ISSUE TITLE
PHP7 incompatibility

### ISSUE THREAD

**Issue by pascalwacker** [dantleech/glob#3]
Hi  
I tried to run some project on a PHP7 machine, which resulted in the error `PHP Fatal error: Cannot use 'String' as class name as it is reserved in /var/www/foobar/vendor/doctrine/phpcr-odm/lib/Doctrine/ODM/PHPCR/Mapping/Annotations/String.php on line 28`.

I think the issue is described here: doctrine/phpcr-odm#678. As I see it, the issue should be eliminated by updating this bundle to ~1.3 https://github.com/doctrine/DoctrinePHPCRBundle (you require only version ~1.2 https://github.com/dantleech/glob/blob/master/composer.json)  
Thanks in advance for checking (and if it should be the error, fixing it :))

**Comment by dantleech** [comment]
Hi, thanks for reporting this.

This library only provides an adapter for the PHPCR-ODM, it does not use any of the reserved keywords itself, so it is compatible both with PHP 5 and 7, and the PHPCR-ODM dependency is correct.

The issue will be found in another of your liraries which uses the PHP7-reserved PHPCR-ODM annotations.
 
Please reopen if you disagree.
